name: Tests
on:
  push:
    branches: '**'
  pull_request:
    branches: main
jobs:
  unit-testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Install xmllint
        if: runner.os == 'Linux'
        run: sudo apt-get install libxml2-utils
        shell: bash
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set environment variables
        run:  echo "PYTHON_VERSION=$(./python_version.sh)" >> $GITHUB_ENV
        shell: bash
      - name: Display Safe Python Version
        run: echo ${{ env.PYTHON_VERSION }}
        shell: bash
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
